# see: https://taplo.tamasfe.dev/configuration/file.html

# see: https://taplo.tamasfe.dev/configuration/formatter-options.html
[formatting]
  allowed_blank_lines = 1
  column_width = 100
  compact_entries = false
  indent_entries = true
  reorder_arrays = true
  reorder_keys = true
