add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[docker_context]
disabled = true

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$context(\[$namespace\])]($style) '


[python]
pyenv_version_name = true
