# see: https://starship.rs/config/
# see: https://starship.rs/presets/nerd-font.html

# Avoid a newline at the top of the shell (handled by my preexec and precmd functions)
add_newline = false

# Give pyenv, etc more time
command_timeout = 9999999999

# First line = left components + middle fill + right components
# Second line = character + prompt
format = """
$directory\
$cmd_duration\
$fill\
$git_branch\
$nodejs\
$python\
$kubernetes\
$gcloud\
$all\
$line_break\
$character\
"""

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
style = "#B4BEFE bold"
truncate_to_repo = true
truncation_length = 3

[docker_context]
disabled = true
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

# Keep left/right prompt on same line while adding a newline for the prompt input:
# https://starship.rs/config/#fill
# https://www.youtube.com/watch?v=VgTu1_92U0U
[fill]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
detect_env_vars = ['STARSHIP_SHOW_GCLOUD_COMPONENT']
format = ' [$symbol$project]($style)'
symbol = ''
# symbol = '󰅟  '
# symbol = "  "

[gcloud.project_aliases]
rp006-prod-49a893d8 = 'rp006-prod'

[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'an1'

[git_branch]
format = '[$symbol$branch]($style)'
symbol = " "
# style = "bright-black"

[git_status]
disabled = true

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile', 'docker-compose.yml', 'Kubernetesfile', 'helmfile.yaml']
detect_folders = ['k8s', '.k8s', 'k8s-config', '.k8s-config', 'deploy', '.deploy']
format = ' [$context:$namespace]($style)'

[[kubernetes.contexts]]
context_pattern = 'gke_rp006-prod-49a893d8_us-central1_rp006-prod'
context_alias = 'rp006-prod'

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
detect_extensions=[]
detect_files=['package.json']
detect_folders=[]
format = ' [$symbol$version]($style)'
symbol = ""
# symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
disabled = true
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
# detect_extensions = []
# detect_files=[]
format = ' [${symbol}(${version})( \($virtualenv\))]($style)'
symbol = ""
# symbol = " "
version_format = "${raw}"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

