# see: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# colours: black | red | green | yellow | blue | magenta | cyan | white | '#ff00ff'
# modifiers: bold | default | reverse (useful for high-contrast) | underline

git:
  commit:
    verbose: always # 'default' | 'always' | 'never' (applies to C, not c)

gui:
  expandFocusedSidePanel: true
  parseEmoji: true
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showFileTree: false # for rendering changes files in a tree format
  sidePanelWidth: 0.25 # number from 0 to 1 (default: 0.33333)
  theme:
    selectedLineBgColor:
      - bold
    selectedRangeBgColor:
      - reverse

keybinding:
  branches:
    createRebaseOptionsMenu: "M"
    mergeIntoCurrentBranch: "m"
    rebaseBranch: "R"
    renameBranch: "r"

promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true # "esc" quits when there's nothing to cancel/close
