# see: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# colours: black | red | green | yellow | blue | magenta | cyan | white | '#ff00ff'
# modifiers: bold | default | reverse (useful for high-contrast underline)

git:
  commit:
    verbose: always # 'default' | 'always' | 'never' (applies to C, not c)

gui:
  expandFocusedSidePanel: true
  parseEmoji: true
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showFileTree: false # for rendering changes files in a tree format
  sidePanelWidth: 0.25 # number from 0 to 1 (default: 0.33333)
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

keybinding:
  branches:
    createRebaseOptionsMenu: "M"
    mergeIntoCurrentBranch: "m"
    rebaseBranch: "R"
    renameBranch: "r"

promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true # "esc" quits when there's nothing to cancel/close

# keybinding:
#   universal:
#     quit: 'q'
#     quit-alt1: '<c-c>' # alternative/alias of quit
#     return: '<esc>' # return to previous menu, will quit if there's nowhere to return
#     # When set to a printable character, this will work for returning from non-prompt panels
#     return-alt1: null
#     quitWithoutChangingDirectory: 'Q'
#     togglePanel: '<tab>' # goto the next panel
#     prevItem: '<up>' # go one line up
#     nextItem: '<down>' # go one line down
#     prevItem-alt: 'k' # go one line up
#     nextItem-alt: 'j' # go one line down
#     prevPage: ',' # go to next page in list
#     nextPage: '.' # go to previous page in list
#     gotoTop: '<' # go to top of list
#     gotoBottom: '>' # go to bottom of list
#     scrollLeft: 'H' # scroll left within list view
#     scrollRight: 'L' # scroll right within list view
#     prevBlock: '<left>' # goto the previous block / panel
#     nextBlock: '<right>' # goto the next block / panel
#     prevBlock-alt: 'h' # goto the previous block / panel
#     nextBlock-alt: 'l' # goto the next block / panel
#     jumpToBlock: ['1', '2', '3', '4', '5'] # goto the Nth block / panel
#     nextMatch: 'n'
#     prevMatch: 'N'
#     optionMenu: null # show help menu
#     optionMenu-alt1: '?' # show help menu
#     select: '<space>'
#     goInto: '<enter>'
#     openRecentRepos: '<c-r>'
#     confirm: '<enter>'
#     confirm-alt1: 'y'
#     remove: 'd'
#     new: 'n'
#     edit: 'e'
#     openFile: 'o'
#     scrollUpMain: '<pgup>' # main panel scroll up
#     scrollDownMain: '<pgdown>' # main panel scroll down
#     scrollUpMain-alt1: 'K' # main panel scroll up
#     scrollDownMain-alt1: 'J' # main panel scroll down
#     scrollUpMain-alt2: '<c-u>' # main panel scroll up
#     scrollDownMain-alt2: '<c-d>' # main panel scroll down
#     executeCustomCommand: ':'
#     createRebaseOptionsMenu: 'm'
#     pushFiles: 'P'
#     pullFiles: 'p'
#     refresh: 'R'
#     createPatchOptionsMenu: '<c-p>'
#     nextTab: ']'
#     prevTab: '['
#     nextScreenMode: '+'
#     prevScreenMode: '_'
#     undo: 'z'
#     redo: '<c-z>'
#     filteringMenu: '<c-s>'
#     diffingMenu: 'W'
#     diffingMenu-alt: '<c-e>' # deprecated
#     copyToClipboard: '<c-o>'
#     submitEditorText: '<enter>'
#     appendNewline: '<a-enter>'
#     extrasMenu: '@'
#     toggleWhitespaceInDiffView: '<c-w>'
#     increaseContextInDiffView: '}'
#     decreaseContextInDiffView: '{'
#   status:
#     checkForUpdate: 'u'
#     recentRepos: '<enter>'
#   files:
#     commitChanges: 'c'
#     commitChangesWithoutHook: 'w' # commit changes without pre-commit hook
#     amendLastCommit: 'A'
#     commitChangesWithEditor: 'C'
#     ignoreFile: 'i'
#     refreshFiles: 'r'
#     stashAllChanges: 's'
#     viewStashOptions: 'S'
#     toggleStagedAll: 'a' # stage/unstage all
#     viewResetOptions: 'D'
#     fetch: 'f'
#     toggleTreeView: '`'
#     openMergeTool: 'M'
#     openStatusFilter: '<c-b>'
#   branches:
#     createPullRequest: 'o'
#     viewPullRequestOptions: 'O'
#     checkoutBranchByName: 'c'
#     forceCheckoutBranch: 'F'
#     rebaseBranch: 'r'
#     renameBranch: 'R'
#     mergeIntoCurrentBranch: 'M'
#     viewGitFlowOptions: 'i'
#     fastForward: 'f' # fast-forward this branch from its upstream
#     createTag: 'T'
#     pushTag: 'P'
#     setUpstream: 'u' # set as upstream of checked-out branch
#     fetchRemote: 'f'
#   commits:
#     squashDown: 's'
#     renameCommit: 'r'
#     renameCommitWithEditor: 'R'
#     viewResetOptions: 'g'
#     markCommitAsFixup: 'f'
#     createFixupCommit: 'F' # create fixup commit for this commit
#     squashAboveCommits: 'S'
#     moveDownCommit: '<c-j>' # move commit down one
#     moveUpCommit: '<c-k>' # move commit up one
#     amendToCommit: 'A'
#     pickCommit: 'p' # pick commit (when mid-rebase)
#     revertCommit: 't'
#     cherryPickCopy: 'c'
#     cherryPickCopyRange: 'C'
#     pasteCommits: 'v'
#     tagCommit: 'T'
#     checkoutCommit: '<space>'
#     resetCherryPick: '<c-R>'
#     copyCommitMessageToClipboard: '<c-y>'
#     openLogMenu: '<c-l>'
#     viewBisectOptions: 'b'
#   stash:
#     popStash: 'g'
#     renameStash: 'r'
#   commitFiles:
#     checkoutCommitFile: 'c'
#   main:
#     toggleDragSelect: 'v'
#     toggleDragSelect-alt: 'V'
#     toggleSelectHunk: 'a'
#     pickBothHunks: 'b'
#   submodules:
#     init: 'i'
#     update: 'u'
#     bulkMenu: 'b'
