# see: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# colours: black | red | green | yellow | blue | magenta | cyan | white | '#ff00ff' (any hex code)
# modifiers: bold | default | reverse (useful for high-contrast) | underline

git:
  commit:
    verbose: always # 'default' | 'always' | 'never' (applies to C, not c)

gui:
  expandFocusedSidePanel: true
  parseEmoji: true
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showFileTree: false # for rendering changes files in a tree format
  sidePanelWidth: 0.25 # number from 0 to 1 (default: 0.33333)
  theme:
    # I like this one with the dracula theme, but not with gruvbox
    selectedLineBgColor:
      - '#1A1C25' # material ocean input bg color (see: https://github.com/material-theme/vsc-material-theme/blob/main/scripts/generator/settings/specific/ocean.ts)
    selectedRangeBgColor:
      - reverse

keybinding:
  universal:
    scrollUpMain: "<c-u>" # main panel scroll up
    scrollDownMain: "<c-d>" # main panel scroll down
  branches:
    createRebaseOptionsMenu: "M" # avoid accidental rebasing
    mergeIntoCurrentBranch: "m"
    rebaseBranch: "R" # avoid accidental rebasing
    renameBranch: "r"
  commits:
    amendToCommit: 'a'
    resetCommitAuthor: 'A'

promptToReturnFromSubprocess: false
quitOnTopLevelReturn: false # true means "esc" quits when there's nothing to cancel/close
